### ISSUE TITLE
Bullet traces don't hit wall

### ISSUE THREAD

**Issue by kungfooman** [iosof2mp/iosof2mp#5]
Noticed that on a bunch of maps, the bullets never seem to hit on some walls.

I don't know if this is mostly related to game/cgame surface flags e.g. or deeper in the engine in the actual CM bsp tracing code.

I just wish we had a sack full of BSP unit tests to catch these filthy bugs.

**Comment by AJSchat** [comment]
Hi there!

What walls are you referring to? Did you by any chance encounter one while making the video posted in the other issue, #3?

My working directory already contains the original SoF2MP content bits, surface flags and content flags but are added pragmatically, I need to verify and finalize the additions still. This also allows for normal movement when walking. I'll get these changes committed soon.

It should fix this issue, if you can help me pinpoint the location of where this happened I can verify if this is indeed the case.

Thank you for reporting!

**Comment by kungfooman** [comment]
Hey!

Yea, in the first video I encountered a few missed bullet traces, but I made a proper video now for `mp_shop`: https://www.youtube.com/watch?v=QXZr0u5JShA

E.g. shooting the door at the end of the video works, but at the same time it shows water bubbles, so probably a mixup of surface/content flags.

**Comment by AJSchat** [comment]
Thanks for the video! I verified that the addition of the proper game content and surface flags does indeed fix the issue. Movement should also be fine now.

Thanks again for reporting!
